/**
   Navigation
 **/

export const NAVIGATE_TO = "NAVIGATE_TO";

export const AUTH_REQUEST_ID_VALIDATION_SUCCEDED = "AUTH_REQUEST_ID_VALIDATION_SUCCEDED";
export const AUTH_REQUEST_ID_VALIDATION_FAILED = "AUTH_REQUEST_ID_VALIDATION_FAILED";

export const INSITUTION_CONNECTED = "INSITUTION_CONNECTED";

export const SMS_CODE_CHANGED = "SMS_CODE_CHANGED";
export const SMS_CODE_SUBMITED = "SMS_CODE_SUBMITED";
export const SMS_CODE_VALIDATION_SUCCEDED = "SMS_CODE_VALIDATION_SUCCEDED";
export const SMS_CODE_SENT = "SMS_CODE_SENT";
export const SMS_CODE_VALIDATION_FAILED = "SMS_CODE_VALIDATION_FAILED";
export const SMS_CODE_RESEND_STARTED = "SMS_CODE_RESEND_STARTED";

export const FILE_UPLOAD_STARTED = "FILE_UPLOAD_STARTED";
export const FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED";
export const FILE_UPLOAD_SUCCEDED = "FILE_UPLOAD_SUCCEDED";

export const INSTITUTIONS_FETCHED = "INSTITUTIONS_FETCHED";
export const INSTITUTIONS_FETCH_FAILED = "INSTITUTIONS_FETCH_FAILED";

export const INPUT_METHOD_SELECTED = "INPUT_METHOD_SELECTED";
export const INSTITUTION_SELECTED = "INSTITUTION_SELECTED";

export const UPLOAD_PAGE_FINISHED = "UPLOAD_PAGE_FINISHED";

export const BANK_CONNECT_STARTED = "BANK_CONNECT_STARTED";
export const BANK_CONNECT_FAILED = "BANK_CONNECT_FAILED";
export const BANK_CONNECT_SUCCEDED = "BANK_CONNECT_SUCCEDED";
export const BANK_CONNECT_FINISHED = "BANK_CONNECT_FINISHED";

export const CONNECT_CREDENTIALS_VALIDATION_FAILED = "CONNECT_CREDENTIALS_VALIDATION_FAILED";
export const VERIFY_CREDENTIALS_FAILED = "VERIFY_CREDENTIALS_FAILED";

export const LOGIN_ID_CHANGED = "LOGIN_ID_CHANGED";
export const SECONDARY_LOGIN_ID_CHANGED = "SECONDARY_LOGIN_ID_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const SECURITY_CODE_CHANGED = "SECURITY_CODE_CHANGED";

export const UNSUPPORTED_FILE_DROPPED = "UNSUPPORTED_FILE_DROPPED";
export const LARGE_FILE_DROPPED = "LARGE_FILE_DROPPED";
export const FILE_REMOVED = "FILE_REMOVED";
export const FILE_ADDED = "FILE_ADDED";

export const TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED";
export const TOKEN_VALIDATION_SUCCEDED = "TOKEN_VALIDATION_SUCCEDED";
export const AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED";
export const AUTH_LINK_DISABLE_STARTED = "AUTH_LINK_DISABLE_STARTED";
export const AUTH_LINK_DISABLE_SUCCESS = "AUTH_LINK_DISABLE_SUCCESS";
export const AUTH_LINK_DISABLE_FAILED = "AUTH_LINK_DISABLE_FAILED";
